project_id = "fvpglbppmmexcysuumth"

[functions.create-order]
verify_jwt = false

[functions.order-status]
verify_jwt = false

[functions.click]
verify_jwt = false

[functions.crypto-payment-instructions]
verify_jwt = false

[functions.verify-crypto-payment]
verify_jwt = false

[functions.dodo-checkout]
verify_jwt = false

[functions.dodo-webhook]
verify_jwt = false
